### ISSUE TITLE
TypeError: write() got an unexpected keyword argument 'stop'

### ISSUE THREAD

**Issue by wkirby007** [fourstix/Sparkfun_CircuitPython_QwiicAS3935#3]
When running example 1 from the library, I get the following error using I2C.

AS3935 Franklin Lightning Detector
Traceback (most recent call last):
  File "tune.py", line 34, in <module>
    if lightning.connected:
  File "/usr/local/lib/python3.7/dist-packages/sparkfun_qwiicas3935.py", line 285, in connected
    value = self._read_register(_AFE_GAIN)
  File "/usr/local/lib/python3.7/dist-packages/sparkfun_qwiicas3935.py", line 556, in _read_register
    i2c.write(bytes([0x00]), stop=False)
TypeError: write() got an unexpected keyword argument 'stop'

**Comment by fourstix** [comment]
Stop is no longer supported. It needs to be removed.

**Comment by fourstix** [comment]
Removed stop=False parameter.  Need to update the build to publish fix.
